services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/api_scaffold_development
      REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: password
      CONTAINER_ROLE: web
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - gems:/usr/local/bundle

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/api_scaffold_development
      REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: password
      CONTAINER_ROLE: worker
    depends_on:
      - web
      - redis
    volumes:
      - .:/app
      - gems:/usr/local/bundle

  db:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    ports:
      - "6380:6379"

volumes:
  postgres:
  redis:
  gems: 